// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagePayment } from '../models';
// @ts-ignore
import { Payment } from '../models';
/**
 * PaymentControllerApi - axios parameter creator
 * @export
 */
export const PaymentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getInfo_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo2: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getInfo2.');
            }
            const localVarPath = `/payments/getInfo/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getInfo_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo2_1: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getInfo2_1.');
            }
            const localVarPath = `/payments/getInfo/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary list_2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list2: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary list_2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list2_2: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary page_2
         * @param {Array<Payment>} [records] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {number} [totalPage] 
         * @param {number} [totalRow] 
         * @param {boolean} [optimizeCountQuery] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        page2: async (records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/page`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (records) {
                localVarQueryParameter['records'] = records;
            }

            if (pageNumber !== undefined) {
                localVarQueryParameter['pageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (totalPage !== undefined) {
                localVarQueryParameter['totalPage'] = totalPage;
            }

            if (totalRow !== undefined) {
                localVarQueryParameter['totalRow'] = totalRow;
            }

            if (optimizeCountQuery !== undefined) {
                localVarQueryParameter['optimizeCountQuery'] = optimizeCountQuery;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary page_2
         * @param {Array<Payment>} [records] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {number} [totalPage] 
         * @param {number} [totalRow] 
         * @param {boolean} [optimizeCountQuery] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        page2_3: async (records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/page`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (records) {
                localVarQueryParameter['records'] = records;
            }

            if (pageNumber !== undefined) {
                localVarQueryParameter['pageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (totalPage !== undefined) {
                localVarQueryParameter['totalPage'] = totalPage;
            }

            if (totalRow !== undefined) {
                localVarQueryParameter['totalRow'] = totalRow;
            }

            if (optimizeCountQuery !== undefined) {
                localVarQueryParameter['optimizeCountQuery'] = optimizeCountQuery;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary remove_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove2: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling remove2.');
            }
            const localVarPath = `/payments/remove/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary remove_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove2_4: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling remove2_4.');
            }
            const localVarPath = `/payments/remove/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary save_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        save2: async (payment?: Payment, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof payment !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(payment !== undefined ? payment : {}) : (payment || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary save_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        save2_5: async (payment?: Payment, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/save`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof payment !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(payment !== undefined ? payment : {}) : (payment || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary update_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2: async (payment?: Payment, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/update`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof payment !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(payment !== undefined ? payment : {}) : (payment || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary update_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2_6: async (payment?: Payment, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/update`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof payment !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(payment !== undefined ? payment : {}) : (payment || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentControllerApi - functional programming interface
 * @export
 */
export const PaymentControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getInfo_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInfo2(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).getInfo2(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getInfo_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInfo2_1(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).getInfo2_1(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary list_2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list2(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Payment>>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).list2(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary list_2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list2_2(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Payment>>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).list2_2(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary page_2
         * @param {Array<Payment>} [records] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {number} [totalPage] 
         * @param {number} [totalRow] 
         * @param {boolean} [optimizeCountQuery] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async page2(records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagePayment>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).page2(records, pageNumber, pageSize, totalPage, totalRow, optimizeCountQuery, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary page_2
         * @param {Array<Payment>} [records] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {number} [totalPage] 
         * @param {number} [totalRow] 
         * @param {boolean} [optimizeCountQuery] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async page2_3(records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagePayment>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).page2_3(records, pageNumber, pageSize, totalPage, totalRow, optimizeCountQuery, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary remove_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove2(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).remove2(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary remove_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async remove2_4(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).remove2_4(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary save_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async save2(payment?: Payment, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).save2(payment, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary save_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async save2_5(payment?: Payment, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).save2_5(payment, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary update_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update2(payment?: Payment, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).update2(payment, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary update_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update2_6(payment?: Payment, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await PaymentControllerApiAxiosParamCreator(configuration).update2_6(payment, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PaymentControllerApi - factory interface
 * @export
 */
export const PaymentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary getInfo_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo2(id: number, options?: any): AxiosPromise<Payment> {
            return PaymentControllerApiFp(configuration).getInfo2(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getInfo_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInfo2_1(id: number, options?: any): AxiosPromise<Payment> {
            return PaymentControllerApiFp(configuration).getInfo2_1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary list_2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list2(options?: any): AxiosPromise<Array<Payment>> {
            return PaymentControllerApiFp(configuration).list2(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary list_2
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list2_2(options?: any): AxiosPromise<Array<Payment>> {
            return PaymentControllerApiFp(configuration).list2_2(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary page_2
         * @param {Array<Payment>} [records] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {number} [totalPage] 
         * @param {number} [totalRow] 
         * @param {boolean} [optimizeCountQuery] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        page2(records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options?: any): AxiosPromise<PagePayment> {
            return PaymentControllerApiFp(configuration).page2(records, pageNumber, pageSize, totalPage, totalRow, optimizeCountQuery, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary page_2
         * @param {Array<Payment>} [records] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {number} [totalPage] 
         * @param {number} [totalRow] 
         * @param {boolean} [optimizeCountQuery] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        page2_3(records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options?: any): AxiosPromise<PagePayment> {
            return PaymentControllerApiFp(configuration).page2_3(records, pageNumber, pageSize, totalPage, totalRow, optimizeCountQuery, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary remove_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove2(id: number, options?: any): AxiosPromise<boolean> {
            return PaymentControllerApiFp(configuration).remove2(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary remove_2
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        remove2_4(id: number, options?: any): AxiosPromise<boolean> {
            return PaymentControllerApiFp(configuration).remove2_4(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary save_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        save2(payment?: Payment, options?: any): AxiosPromise<boolean> {
            return PaymentControllerApiFp(configuration).save2(payment, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary save_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        save2_5(payment?: Payment, options?: any): AxiosPromise<boolean> {
            return PaymentControllerApiFp(configuration).save2_5(payment, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary update_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2(payment?: Payment, options?: any): AxiosPromise<boolean> {
            return PaymentControllerApiFp(configuration).update2(payment, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary update_2
         * @param {Payment} [payment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2_6(payment?: Payment, options?: any): AxiosPromise<boolean> {
            return PaymentControllerApiFp(configuration).update2_6(payment, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentControllerApi - object-oriented interface
 * @export
 * @class PaymentControllerApi
 * @extends {BaseAPI}
 */
export class PaymentControllerApi extends BaseAPI {
    /**
     * 
     * @summary getInfo_2
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public getInfo2(id: number, options?: any) {
        return PaymentControllerApiFp(this.configuration).getInfo2(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getInfo_2
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public getInfo2_1(id: number, options?: any) {
        return PaymentControllerApiFp(this.configuration).getInfo2_1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary list_2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public list2(options?: any) {
        return PaymentControllerApiFp(this.configuration).list2(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary list_2
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public list2_2(options?: any) {
        return PaymentControllerApiFp(this.configuration).list2_2(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary page_2
     * @param {Array<Payment>} [records] 
     * @param {number} [pageNumber] 
     * @param {number} [pageSize] 
     * @param {number} [totalPage] 
     * @param {number} [totalRow] 
     * @param {boolean} [optimizeCountQuery] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public page2(records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options?: any) {
        return PaymentControllerApiFp(this.configuration).page2(records, pageNumber, pageSize, totalPage, totalRow, optimizeCountQuery, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary page_2
     * @param {Array<Payment>} [records] 
     * @param {number} [pageNumber] 
     * @param {number} [pageSize] 
     * @param {number} [totalPage] 
     * @param {number} [totalRow] 
     * @param {boolean} [optimizeCountQuery] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public page2_3(records?: Array<Payment>, pageNumber?: number, pageSize?: number, totalPage?: number, totalRow?: number, optimizeCountQuery?: boolean, options?: any) {
        return PaymentControllerApiFp(this.configuration).page2_3(records, pageNumber, pageSize, totalPage, totalRow, optimizeCountQuery, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary remove_2
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public remove2(id: number, options?: any) {
        return PaymentControllerApiFp(this.configuration).remove2(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary remove_2
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public remove2_4(id: number, options?: any) {
        return PaymentControllerApiFp(this.configuration).remove2_4(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary save_2
     * @param {Payment} [payment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public save2(payment?: Payment, options?: any) {
        return PaymentControllerApiFp(this.configuration).save2(payment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary save_2
     * @param {Payment} [payment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public save2_5(payment?: Payment, options?: any) {
        return PaymentControllerApiFp(this.configuration).save2_5(payment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary update_2
     * @param {Payment} [payment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public update2(payment?: Payment, options?: any) {
        return PaymentControllerApiFp(this.configuration).update2(payment, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary update_2
     * @param {Payment} [payment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentControllerApi
     */
    public update2_6(payment?: Payment, options?: any) {
        return PaymentControllerApiFp(this.configuration).update2_6(payment, options).then((request) => request(this.axios, this.basePath));
    }

}
