// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/alert-controller-api';
export * from './apis/auth-api';
export * from './apis/boat-controller-api';
export * from './apis/boat-type-controller-api';
export * from './apis/dock-controller-api';
export * from './apis/order-controller-api';
export * from './apis/payment-controller-api';
export * from './apis/ticket-controller-api';
export * from './apis/user-controller-api';

