// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Boat } from './boat';

/**
 * 
 * @export
 * @interface Alert
 */
export interface Alert {
    /**
     * 
     * @type {boolean}
     * @memberof Alert
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Alert
     */
    alertId?: number;
    /**
     * 
     * @type {number}
     * @memberof Alert
     */
    boatId?: number;
    /**
     * 
     * @type {Boat}
     * @memberof Alert
     */
    boat?: Boat;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    alertType?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    alertTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Alert
     */
    status?: number;
}


