// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BoatType } from './boat-type';

/**
 * 
 * @export
 * @interface Boat
 */
export interface Boat {
    /**
     * 
     * @type {boolean}
     * @memberof Boat
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Boat
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Boat
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Boat
     */
    boatId?: number;
    /**
     * 
     * @type {string}
     * @memberof Boat
     */
    boatName?: string;
    /**
     * 
     * @type {number}
     * @memberof Boat
     */
    boatTypeId?: number;
    /**
     * 
     * @type {BoatType}
     * @memberof Boat
     */
    boatType?: BoatType;
    /**
     * 
     * @type {number}
     * @memberof Boat
     */
    status?: number;
}


