// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { User } from './user';

/**
 * 
 * @export
 * @interface Code
 */
export interface Code {
    /**
     * 
     * @type {boolean}
     * @memberof Code
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Code
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Code
     */
    userId?: number;
    /**
     * 
     * @type {User}
     * @memberof Code
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    requestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Code
     */
    expirationTime?: string;
}


