// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Order } from './order';

/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {boolean}
     * @memberof Payment
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    paymentId?: number;
    /**
     * 
     * @type {Order}
     * @memberof Payment
     */
    order?: Order;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    paymentTime?: string;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    paymentMethod?: number;
}


