// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponseBoolean
 */
export interface ResponseBoolean {
    /**
     * 
     * @type {number}
     * @memberof ResponseBoolean
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseBoolean
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResponseBoolean
     */
    data?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResponseBoolean
     */
    time?: number;
}


