// tslint:disable
/**
 * 基于物联网的共享智能电动游船管理平台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Boat } from './boat';
import { Dock } from './dock';
import { User } from './user';

/**
 * 
 * @export
 * @interface Ticket
 */
export interface Ticket {
    /**
     * 
     * @type {boolean}
     * @memberof Ticket
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof Ticket
     */
    ticketId?: number;
    /**
     * 
     * @type {number}
     * @memberof Ticket
     */
    userId?: number;
    /**
     * 
     * @type {User}
     * @memberof Ticket
     */
    user?: User;
    /**
     * 
     * @type {number}
     * @memberof Ticket
     */
    boatId?: number;
    /**
     * 
     * @type {Boat}
     * @memberof Ticket
     */
    boat?: Boat;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    endTime?: string;
    /**
     * 
     * @type {Dock}
     * @memberof Ticket
     */
    departureDock?: Dock;
    /**
     * 
     * @type {Dock}
     * @memberof Ticket
     */
    destinationDock?: Dock;
    /**
     * 
     * @type {number}
     * @memberof Ticket
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof Ticket
     */
    remainingTickets?: number;
}


